Implemented solution for hw24
andriylagun/internet-shop pull request #3
Opened 2020-09-02 14:51 UTC by andriylagun

2020-09-02 16:18 UTC, Rommelua commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +                .orElseThrow();
In this method you doesn't update product in storage.

2020-09-02 16:22 UTC, Rommelua commented on src/main/java/Application.java
> +        productService.update(greenTeaProduct);
You have changed price when invoked setPrice(), not update() 
Use to find mistake
```
Product productToUpdate = new Product("Xiaomi Redmi Note 6", 400.0);
        productToUpdate.setId(2L);
        productService.update(productToUpdate);
```

2020-09-02 16:24 UTC, Rommelua commented on src/main/java/com/internet/shop/dao/impl/UserDaoImpl.java
> +    public User getUserById(long id) {
We should return Optional here

2020-09-02 16:32 UTC, Rommelua commented on src/main/java/com/internet/shop/model/Order.java
> +    private static long idCount = 1;
Of course, this logic will work to, but in task we were asked to make increment in Storage...

2020-09-02 16:35 UTC, Rommelua commented
Good job!

2020-09-03 09:15 UTC, KseniiaMakarova requested changes

2020-09-03 09:15 UTC, KseniiaMakarova commented on .travis.yml
> +    - $HOME/.m2
your master already contains this file

2020-09-03 09:15 UTC, KseniiaMakarova commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
let's remove junit dependency and commented line

2020-09-03 09:15 UTC, KseniiaMakarova commented on src/main/java/Application.java
> +public class Application {
put this class inside `com.internet.shop`

2020-09-03 09:15 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/UserDao.java
> +public interface UserDao {
currently we don't need to write methods here
please remove this for now

2020-09-03 09:15 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +    }
the logic of this method is to update all possible matches, not only the first one

let's create IntStream of indices, than filter out only those indices on which there are elements with the same id
then for each of the remaining indices, replace the element with our `product`

and let's return the new product (actually return the same object that we receive)

2020-09-03 09:15 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/UserDaoImpl.java
> +public class UserDaoImpl implements UserDao {
let's remove this

2020-09-03 09:15 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/db/Storage.java
> +    private static long orderId = 1;
```suggestion
    private static Long userId = 0L;
    private static Long productId = 0L;
    private static Long shoppingCartId = 0L;
    private static Long orderId = 0L;
```

2020-09-03 09:15 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/db/Storage.java
> +        user.setId(userId++);
```suggestion
        user.setId(++userId);
```
same for other methods

2020-09-03 09:15 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/Order.java
> +        this.products = products;
what does this line mean?

2020-09-03 09:15 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/ShoppingCart.java
> +        this.userId = userId;
let's initialize `products` here as well

2020-09-03 09:15 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/service/impl/ProductServiceImpl.java
> +        return productDao.get(id).orElseThrow();
let's use `get()` for now

2020-09-03 09:15 UTC, KseniiaMakarova commented on src/main/java/Application.java
> +        productToUpdate.setId(2L);
let's save our products in variables
and then call `someProduct.getId()` if needed

2020-09-03 09:15 UTC, KseniiaMakarova commented on src/main/java/Application.java
> +        System.out.println(productService.get(XIAOMI_ID));
same here

2020-09-03 13:18 UTC, KseniiaMakarova approved these changes

2020-09-03 13:40 UTC, merged